openapi: 3.0.1
info:
  title: monster-mummy-lord
  x-cortex-tag: monster-mummy-lord
  x-cortex-custom-metadata:
    alignment: neutral
    type: fey
    challenge_rating: 28
    legendary: true
    armor_class: 20
    hit_points: 241
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-mummy-lord
      alias: github-token-test
